apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: markoambrozic/catalog:1.0.6
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: dbuser
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres