apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: markoambrozic/orders:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: dbuser
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres